name: Create Release

on:
  push:
    branches:
      - main
      - 'feature/**'
      - 'v*'
      - 'bugfix/'

jobs:
  # JOB 1: Build on Windows (This job remains unchanged)
  build:
    name: Build on Windows
    runs-on: windows-latest
    outputs:
      artifact_name: ${{ steps.get_artifact.outputs.ARTIFACT_NAME }}
      tag_name: ${{ steps.get_version.outputs.TAG_NAME }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
      - name: Install Nerdbank.GitVersioning tool
        run: dotnet tool install -g nbgv
      - name: Restore dependencies
        run: dotnet tool restore
      - name: Run Cake build and package
        run: dotnet cake --target=Package --configuration=Release
      - name: Run Unit & Integration Tests
        run: dotnet test --configuration Release --no-build --verbosity normal
      - name: Get Release Version
        id: get_version
        run: echo "TAG_NAME=v$(nbgv get-version -v NuGetPackageVersion)" >> $env:GITHUB_OUTPUT
        shell: pwsh
      - name: Get Artifact Details
        id: get_artifact
        shell: pwsh
        run: |
          $artifact = Get-ChildItem ./artifacts/*.zip | Select-Object -First 1
          echo "ARTIFACT_NAME=$($artifact.Name)" >> $env:GITHUB_OUTPUT
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: verity-package
          path: ./artifacts/${{ steps.get_artifact.outputs.ARTIFACT_NAME }}

  # JOB 2: Create the Release on Linux (This job is corrected)
  release:
    name: Create Release on Linux
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write 
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: verity-package
          
      - name: Generate Changelog File
        id: cliff
        uses: orhun/git-cliff-action@v4
        with:
          config: cliff.toml
          
      - name: Prepare Release Body
        id: prep_body
        shell: bash
        run: |
          # Read the content of the generated changelog file into a variable
          CHANGELOG_CONTENT=$(cat ${{ steps.cliff.outputs.changelog }})

          # Capture the previous tag, if it exists
          PREVIOUS_TAG="${{ steps.cliff.outputs.previous_tag }}"
          
          # Start with the main changelog content
          BODY="$CHANGELOG_CONTENT"

          # Only add the "Full Changelog" link if a previous tag was found
          if [[ -n "$PREVIOUS_TAG" ]]; then
            # Append a newline and the link to the body
            BODY+=$'\n\n**Full Changelog**: https://github.com/${{ github.repository }}/compare/${PREVIOUS_TAG}...${{ needs.build.outputs.tag_name }}'
          fi

          # Use a heredoc to safely pass the final multiline body to the output
          echo 'body<<EOF' >> $GITHUB_OUTPUT
          echo "$BODY" >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT
          
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ needs.build.outputs.tag_name }}
          name: Release ${{ needs.build.outputs.tag_name }}
          # Use the fully prepared body from the previous step
          body: ${{ steps.prep_body.outputs.body }}
          files: ${{ needs.build.outputs.artifact_name }}
          prerelease: ${{ startsWith(github.ref, 'refs/heads/feature/') }}